/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculator;

import java.awt.Toolkit;

/**
 *
 * @author Nishchal
 */
public class Calculator extends javax.swing.JFrame{

    /**
     * Creates new form Calculator
     */
    double fn=0, sn=0, result=0;
    int decimal=0, ecount=0;
    char op=0;
    public Calculator() {
        initComponents();
        setIcon();
    }
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("3.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sq = new javax.swing.JButton();
        pw = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        bsub = new javax.swing.JButton();
        root = new javax.swing.JButton();
        rem = new javax.swing.JButton();
        log = new javax.swing.JButton();
        exp = new javax.swing.JButton();
        fac = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        bdiv = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        bmul = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        bneg = new javax.swing.JButton();
        badd = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        euler = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        rub = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bd = new javax.swing.JButton();
        cal = new javax.swing.JButton();
        txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        show = new javax.swing.JTextField();
        cr = new javax.swing.JButton();
        asin = new javax.swing.JButton();
        acos = new javax.swing.JButton();
        atan = new javax.swing.JButton();
        pi = new javax.swing.JButton();
        cu = new javax.swing.JButton();
        prck = new javax.swing.JButton();
        arms = new javax.swing.JButton();
        unit = new javax.swing.JButton();
        exiter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator- By Nishchal");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(668, 616));
        setMinimumSize(new java.awt.Dimension(668, 616));
        setName("calculator"); // NOI18N
        setResizable(false);

        sq.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        sq.setText("x^2");
        sq.setToolTipText("Square");
        sq.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sq.setName(""); // NOI18N
        sq.setPreferredSize(new java.awt.Dimension(65, 35));
        sq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqActionPerformed(evt);
            }
        });

        pw.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        pw.setText("x^y");
        pw.setToolTipText("Power");
        pw.setName(""); // NOI18N
        pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwActionPerformed(evt);
            }
        });

        cos.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cos.setText("cos");
        cos.setToolTipText("cosine");
        cos.setName(""); // NOI18N
        cos.setPreferredSize(new java.awt.Dimension(65, 35));
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });

        sin.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        sin.setText("sin");
        sin.setToolTipText("sine");
        sin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sin.setName(""); // NOI18N
        sin.setPreferredSize(new java.awt.Dimension(65, 35));
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });

        tan.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tan.setText("tan");
        tan.setToolTipText("tangent");
        tan.setMaximumSize(null);
        tan.setMinimumSize(null);
        tan.setName(""); // NOI18N
        tan.setPreferredSize(new java.awt.Dimension(65, 35));
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });

        bsub.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bsub.setText("-");
        bsub.setToolTipText("Subtraction");
        bsub.setName(""); // NOI18N
        bsub.setPreferredSize(new java.awt.Dimension(65, 35));
        bsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsubActionPerformed(evt);
            }
        });

        root.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        root.setText("sq. root");
        root.setToolTipText("Square Root");
        root.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        root.setName(""); // NOI18N
        root.setPreferredSize(new java.awt.Dimension(65, 35));
        root.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rootActionPerformed(evt);
            }
        });

        rem.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        rem.setText("%");
        rem.setToolTipText("Remainder (%)");
        rem.setName(""); // NOI18N
        rem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remActionPerformed(evt);
            }
        });

        log.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        log.setText("log");
        log.setToolTipText("Logarithm");
        log.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        log.setMaximumSize(null);
        log.setMinimumSize(null);
        log.setName(""); // NOI18N
        log.setPreferredSize(new java.awt.Dimension(65, 35));
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        exp.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        exp.setText("Exp");
        exp.setToolTipText("Exponent");
        exp.setMaximumSize(null);
        exp.setMinimumSize(null);
        exp.setName(""); // NOI18N
        exp.setPreferredSize(new java.awt.Dimension(65, 35));
        exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expActionPerformed(evt);
            }
        });

        fac.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        fac.setText("n!");
        fac.setToolTipText("Factorial");
        fac.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fac.setMaximumSize(null);
        fac.setMinimumSize(null);
        fac.setName(""); // NOI18N
        fac.setPreferredSize(new java.awt.Dimension(65, 35));
        fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facActionPerformed(evt);
            }
        });

        b7.setBackground(new java.awt.Color(250, 242, 242));
        b7.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        b7.setText("7");
        b7.setToolTipText("7");
        b7.setMaximumSize(null);
        b7.setMinimumSize(null);
        b7.setName(""); // NOI18N
        b7.setPreferredSize(new java.awt.Dimension(65, 35));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setBackground(new java.awt.Color(250, 242, 242));
        b8.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        b8.setText("8");
        b8.setToolTipText("8");
        b8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b8.setMaximumSize(null);
        b8.setMinimumSize(null);
        b8.setName(""); // NOI18N
        b8.setPreferredSize(new java.awt.Dimension(65, 35));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setBackground(new java.awt.Color(250, 242, 242));
        b9.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        b9.setText("9");
        b9.setToolTipText("9");
        b9.setMaximumSize(null);
        b9.setMinimumSize(null);
        b9.setName(""); // NOI18N
        b9.setPreferredSize(new java.awt.Dimension(65, 35));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        bdiv.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        bdiv.setText("/");
        bdiv.setToolTipText("Division");
        bdiv.setName(""); // NOI18N
        bdiv.setPreferredSize(new java.awt.Dimension(65, 35));
        bdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdivActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(250, 242, 242));
        b4.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        b4.setText("4");
        b4.setToolTipText("4");
        b4.setMaximumSize(null);
        b4.setMinimumSize(null);
        b4.setName(""); // NOI18N
        b4.setPreferredSize(new java.awt.Dimension(65, 35));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(250, 242, 242));
        b6.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        b6.setText("6");
        b6.setToolTipText("6");
        b6.setMaximumSize(null);
        b6.setMinimumSize(null);
        b6.setName(""); // NOI18N
        b6.setPreferredSize(new java.awt.Dimension(65, 35));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        bmul.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        bmul.setText("X");
        bmul.setToolTipText("Product");
        bmul.setName(""); // NOI18N
        bmul.setPreferredSize(new java.awt.Dimension(65, 35));
        bmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmulActionPerformed(evt);
            }
        });

        b5.setBackground(new java.awt.Color(250, 242, 242));
        b5.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        b5.setText("5");
        b5.setToolTipText("5");
        b5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b5.setMaximumSize(null);
        b5.setMinimumSize(null);
        b5.setName(""); // NOI18N
        b5.setPreferredSize(new java.awt.Dimension(65, 35));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        bneg.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        bneg.setText("+/-");
        bneg.setToolTipText("Sign change");
        bneg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bneg.setMaximumSize(null);
        bneg.setMinimumSize(null);
        bneg.setName(""); // NOI18N
        bneg.setPreferredSize(new java.awt.Dimension(65, 35));
        bneg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnegActionPerformed(evt);
            }
        });

        badd.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        badd.setText("+");
        badd.setToolTipText("Addition");
        badd.setName(""); // NOI18N
        badd.setPreferredSize(new java.awt.Dimension(65, 35));
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(250, 242, 242));
        b3.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        b3.setText("3");
        b3.setToolTipText("3");
        b3.setMaximumSize(null);
        b3.setMinimumSize(null);
        b3.setName(""); // NOI18N
        b3.setPreferredSize(new java.awt.Dimension(65, 35));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(250, 242, 242));
        b2.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        b2.setText("2");
        b2.setToolTipText("2");
        b2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b2.setMaximumSize(null);
        b2.setMinimumSize(null);
        b2.setName(""); // NOI18N
        b2.setPreferredSize(new java.awt.Dimension(65, 35));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        euler.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        euler.setText("e^x");
        euler.setToolTipText("Euler,s Number");
        euler.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        euler.setName(""); // NOI18N
        euler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eulerActionPerformed(evt);
            }
        });

        b1.setBackground(new java.awt.Color(250, 242, 242));
        b1.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        b1.setText("1");
        b1.setToolTipText("1");
        b1.setMaximumSize(null);
        b1.setMinimumSize(null);
        b1.setName(""); // NOI18N
        b1.setPreferredSize(new java.awt.Dimension(65, 35));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        clear.setText("C");
        clear.setToolTipText("Clear");
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clear.setName(""); // NOI18N
        clear.setPreferredSize(new java.awt.Dimension(65, 35));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        rub.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        rub.setText("<-");
        rub.setToolTipText("Backspace");
        rub.setName(""); // NOI18N
        rub.setPreferredSize(new java.awt.Dimension(65, 35));
        rub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rubActionPerformed(evt);
            }
        });

        b0.setBackground(new java.awt.Color(250, 242, 242));
        b0.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        b0.setText("0");
        b0.setToolTipText("0");
        b0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b0.setMaximumSize(null);
        b0.setMinimumSize(null);
        b0.setName(""); // NOI18N
        b0.setPreferredSize(new java.awt.Dimension(65, 35));
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        bd.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        bd.setText(".");
        bd.setToolTipText("Decimal (period)");
        bd.setName(""); // NOI18N
        bd.setPreferredSize(new java.awt.Dimension(65, 35));
        bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdActionPerformed(evt);
            }
        });

        cal.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cal.setText("=");
        cal.setToolTipText("Calculate");
        cal.setName(""); // NOI18N
        cal.setPreferredSize(new java.awt.Dimension(65, 35));
        cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calActionPerformed(evt);
            }
        });

        txt.setEditable(false);
        txt.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt.setToolTipText("Number");

        jLabel1.setText("DEG");

        show.setEditable(false);
        show.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        show.setToolTipText("Result");
        show.setFocusable(false);

        cr.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cr.setText("Cube Root");
        cr.setToolTipText("Cube root");
        cr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crActionPerformed(evt);
            }
        });

        asin.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        asin.setText("asin");
        asin.setToolTipText("asine");
        asin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asinActionPerformed(evt);
            }
        });

        acos.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        acos.setText("acos");
        acos.setToolTipText("acosine");
        acos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acosActionPerformed(evt);
            }
        });

        atan.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        atan.setText("atan");
        atan.setToolTipText("atangent");
        atan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atanActionPerformed(evt);
            }
        });

        pi.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        pi.setText("π");
        pi.setToolTipText("π");
        pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piActionPerformed(evt);
            }
        });

        cu.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cu.setText("x^3");
        cu.setToolTipText("Cube");
        cu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuActionPerformed(evt);
            }
        });

        prck.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        prck.setText("Check Prime");
        prck.setToolTipText("Check Prime");
        prck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prckActionPerformed(evt);
            }
        });

        arms.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        arms.setText("Check Armstrong");
        arms.setToolTipText("Check Armstrong");
        arms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                armsActionPerformed(evt);
            }
        });

        unit.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        unit.setText("Converter");
        unit.setToolTipText("Unit Converter");
        unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitActionPerformed(evt);
            }
        });

        exiter.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        exiter.setText("Exit");
        exiter.setToolTipText("Exit");
        exiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exiterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(sq, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pw, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bsub, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(fac, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(bneg, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bmul, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(euler, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(badd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rub, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cr, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(acos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(asin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(atan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(prck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(arms, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(unit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exiter)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(show, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exiter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(asin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sq, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(pw, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(sin, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(cos, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(tan, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(atan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(acos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(rem, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(log, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(exp, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(bsub, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bdiv, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(b9, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(b8, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(b7, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(fac, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bneg, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(b6, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(bmul, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(arms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(badd, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(euler, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(unit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b0, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(cal, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(bd, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(rub, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqActionPerformed
        // TODO add your handling code here:
        fn=Double.parseDouble(txt.getText());
        txt.setText(""+Math.pow(fn,2));
        decimal=0;
    }//GEN-LAST:event_sqActionPerformed

    private void pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwActionPerformed
        // TODO add your handling code here:
        fn=Double.parseDouble(txt.getText());
        op='^';
        if(show.getText().equals(""))
            result=fn;
        else
            result=Math.pow(result,fn);
        show.setText(""+result);
        txt.setText("");
        decimal=0;
    }//GEN-LAST:event_pwActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
        // TODO add your handling code here:
        fn=Double.parseDouble(txt.getText());
        txt.setText(""+(Math.cos(Math.toRadians(fn))));
        decimal=0;
    }//GEN-LAST:event_cosActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
        // TODO add your handling code here:
        fn=Double.parseDouble(txt.getText());
        txt.setText(""+(Math.sin(Math.toRadians(fn))));
        decimal=0;
    }//GEN-LAST:event_sinActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
        // TODO add your handling code here:
        fn=Double.parseDouble(txt.getText());
        if(fn==90){
            txt.setText("Tangent of 90 degrees is Infinite");
        }
        else{
            txt.setText(""+(Math.tan(Math.toRadians(fn))));
        }
        decimal=0;
    }//GEN-LAST:event_tanActionPerformed

    private void bsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsubActionPerformed
        // TODO add your handling code here:
        if(show.getText().equals("")){
        show.setText(txt.getText());
        txt.setText("");
        op='-';
        } else{
        fn=Double.parseDouble(txt.getText());
        op='-';
        result-=fn;
        show.setText(""+result);
        txt.setText("");
        }
        decimal=0;
    }//GEN-LAST:event_bsubActionPerformed

    private void rootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rootActionPerformed
        // TODO add your handling code here:
        fn=Double.parseDouble(txt.getText());
        txt.setText(""+(Math.sqrt(fn)));
        decimal=0;
    }//GEN-LAST:event_rootActionPerformed

    private void remActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remActionPerformed
        // TODO add your handling code here:
        fn=Double.parseDouble(txt.getText());
        op='%';
        if(show.getText().equals("")){
            show.setText(""+fn);
            txt.setText("");
            result=fn;
        }
        else{
            result%=fn;
            show.setText(""+result);
            txt.setText("");
        }
        decimal=0;
    }//GEN-LAST:event_remActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        // TODO add your handling code here:
        fn=Double.parseDouble(txt.getText());
        txt.setText(""+(Math.log(fn)));
        decimal=0;
    }//GEN-LAST:event_logActionPerformed

    private void expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expActionPerformed
        // TODO add your handling code here:
        if(ecount==0)
        {
        txt.setText(txt.getText()+"e"); ecount++;
        }
        decimal=0;
    }//GEN-LAST:event_expActionPerformed

    private void facActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facActionPerformed
        // TODO add your handling code here:
        fn=Double.parseDouble(txt.getText());
        txt.setText(""+factorial(fn));
        decimal=0;
    }//GEN-LAST:event_facActionPerformed

    private double factorial(double num){
        double res=1;
        for(int count=1;count<=num;count++)
            res*=count;
        return res;
    }
    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText()+b7.getText());
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText()+b8.getText());
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText()+b9.getText());
    }//GEN-LAST:event_b9ActionPerformed

    private void bdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdivActionPerformed
        // TODO add your handling code here:
        fn=Double.parseDouble(txt.getText());
        op='/';
        if(show.getText().equals("")){
            result=fn;
            show.setText(""+fn);
            txt.setText("");
        }
        else if(fn==0){
            txt.setText("Error! Can't divide by 0");
            show.setText("Press C to continue!");
        }
        else{
            result/=fn;
            show.setText(""+result);
            txt.setText("");
        }
        decimal=0;
    }//GEN-LAST:event_bdivActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText()+b4.getText());
    }//GEN-LAST:event_b4ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText()+b6.getText());
    }//GEN-LAST:event_b6ActionPerformed

    private void bmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmulActionPerformed
        // TODO add your handling code here:
        fn=Double.parseDouble(txt.getText());
        op='*';
        if(show.getText().equals(""))
            result=fn;
        else
            result*=fn;
        show.setText(""+result);
        txt.setText("");
        decimal=0;
    }//GEN-LAST:event_bmulActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText()+b5.getText());
    }//GEN-LAST:event_b5ActionPerformed

    private void bnegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnegActionPerformed
        // TODO add your handling code here:
        txt.setText(""+Double.parseDouble(txt.getText())*(-1));
    }//GEN-LAST:event_bnegActionPerformed

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
        // TODO add your handling code here:
        fn=Double.parseDouble(txt.getText());
        op='+';
        result+=fn;
        show.setText(""+result);
        txt.setText("");
        decimal=0;
    }
    private void resulter()
    {
        //code here (the same as that when = clicked)
    }//GEN-LAST:event_baddActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText()+b3.getText());
    }//GEN-LAST:event_b3ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText()+b2.getText());
    }//GEN-LAST:event_b2ActionPerformed

    private void eulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eulerActionPerformed
        // TODO add your handling code here:
        txt.setText(""+Math.exp(Double.parseDouble(txt.getText())));
        decimal=0;
    }//GEN-LAST:event_eulerActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText()+b1.getText());
    }//GEN-LAST:event_b1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        txt.setText("");
        show.setText("");
        fn=0;
        sn=0;
        result=0;
        decimal=0;
        op=0;
        decimal=0;
    }//GEN-LAST:event_clearActionPerformed

    private void rubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rubActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText().substring(0,txt.getText().length()-1));
        String checker=txt.getText();
        int dddd=0, eeee=0;
        for(int i=0;i<checker.length();i++){
            if(checker.charAt(i)=='.')
                dddd++;
            if(checker.charAt(i)=='e')
                eeee++;
        }
        if(dddd==0)
            decimal=0;
        if(eeee==0)
            ecount=0;
    }//GEN-LAST:event_rubActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText()+b0.getText());
    }//GEN-LAST:event_b0ActionPerformed

    private void bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdActionPerformed
        // TODO add your handling code here:
        if(decimal==0){
            txt.setText(txt.getText()+".");
            decimal++;
        }
    }//GEN-LAST:event_bdActionPerformed

    private void calActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calActionPerformed
        // TODO add your handling code here:
        if(show.getText().equals("")){
            fn=0;
        }
        if(txt.getText().equals("")){
            sn=0;
        }
        if(show.getText().equals("") && txt.getText().equals("")){}
        else{
        fn=Double.parseDouble(show.getText());
        sn=Double.parseDouble(txt.getText());
        }
        switch(op){
            case '+':
                txt.setText(""+(fn+sn));
                show.setText("");
                op=0;
                break;
            case '-':
                txt.setText(""+(fn-sn));
                show.setText("");
                op=0;
                break;
            case '*':
                txt.setText(""+(fn*sn));
                show.setText("");
                op=0;
                break;
            case '/':
                if(sn!=0){
                txt.setText(""+(fn/sn));
                show.setText("");
                op=0;
                }
                else{
                    txt.setText("Error! Can't divide by 0");
                    show.setText("Press C to continue!");
                    op=0;
                }
                break;
            case '^':
                double vvv=Math.pow(fn,sn);
                txt.setText(""+vvv);
                show.setText("");
                op=0;
                break;
            case '%':
                txt.setText(""+fn%sn);
                show.setText("");
                break;
        }
        fn=0; sn=0; result=0;
        op=0;
        int dddd=0, eeee=0;
        String checker=txt.getText();
        for(int i=0;i<checker.length();i++){
            if(checker.charAt(i)=='.')
                dddd++;
            if(checker.charAt(i)=='e')
                eeee++;
        }
            decimal=dddd;
            ecount=eeee;
    }//GEN-LAST:event_calActionPerformed

    private void asinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asinActionPerformed
        // TODO add your handling code here:
        double c=Double.parseDouble(txt.getText());
        if(c>1 || c<-1){
            txt.setText("asine Not Defined!");
            show.setText("Press C to continue!");
        }
        else{
            txt.setText(""+Math.asin(c)*180/Math.PI);
        }
        decimal=0;
    }//GEN-LAST:event_asinActionPerformed

    private void acosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acosActionPerformed
        // TODO add your handling code here:
        double c=Double.parseDouble(txt.getText());
        if(c>1 || c<-1){
            txt.setText("asine Not Defined!");
            show.setText("Press C to continue!");
        }
        else{
            txt.setText(""+Math.acos(c)*180/Math.PI);
        }
        decimal=0;
    }//GEN-LAST:event_acosActionPerformed

    private void crActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crActionPerformed
        // TODO add your handling code here:
        txt.setText(""+Math.cbrt(Double.parseDouble(txt.getText())));
        decimal=0;
    }//GEN-LAST:event_crActionPerformed

    private void atanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atanActionPerformed
        // TODO add your handling code here:
        txt.setText(""+Math.atan(Double.parseDouble(txt.getText()))*180/Math.PI);
        decimal=0;
    }//GEN-LAST:event_atanActionPerformed

    private void piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piActionPerformed
        // TODO add your handling code here:
        txt.setText(""+Math.PI);
        decimal=0;
    }//GEN-LAST:event_piActionPerformed

    private void cuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuActionPerformed
        // TODO add your handling code here:
        txt.setText(""+Math.pow(Double.parseDouble(txt.getText()),3));
        decimal=0;
    }//GEN-LAST:event_cuActionPerformed

    private void prckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prckActionPerformed
        // TODO add your handling code here:
        double n=Double.parseDouble(txt.getText());
        int m=(int)n;
        if(n!=m){
            txt.setText("Enter Natural Numbers!");
            show.setText("Press C to continue!");
        }
        else{
            int prco=0;
            for(int i=1;i<=n;i++){
                if(n%i==0)
                    prco++;
            }
            if(prco==2){
                txt.setText(m+" is Prime!");
                show.setText("Press C to continue!");
            }
            else{
                txt.setText(m+" is NOT Prime!");
                show.setText("Press C to continue!");
            }
        }
        decimal=0;
    }//GEN-LAST:event_prckActionPerformed

    private void armsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_armsActionPerformed
        // TODO add your handling code here:
        double n=Double.parseDouble(txt.getText());
        int m=(int)n;
        if(n!=m){
            txt.setText("Enter Natural Numbers!");
            show.setText("Press C to continue!");
        }
        else{
            int dig=0, ddd=m, sum=0;
            while(ddd!=0)
            {
                ddd/=10;
                dig++;
            }
            ddd=m;
            while(ddd!=0)
            {
                sum+=Math.pow((ddd%10),dig);
                ddd/=10;
            }
            if(sum==m)
            {
                txt.setText(m+" is Armstrong");
                show.setText("Press C to continue");
            }
            else{
                txt.setText(m+" is NOT Armstrong");
                show.setText("Press C to continue");
            }
        }
        decimal=0;
    }//GEN-LAST:event_armsActionPerformed

    private void unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitActionPerformed
        // TODO add your handling code here:
        Converter conv=new Converter();
        conv.main(null);
    }//GEN-LAST:event_unitActionPerformed

    private void exiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exiterActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exiterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acos;
    private javax.swing.JButton arms;
    private javax.swing.JButton asin;
    private javax.swing.JButton atan;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton badd;
    private javax.swing.JButton bd;
    private javax.swing.JButton bdiv;
    private javax.swing.JButton bmul;
    private javax.swing.JButton bneg;
    private javax.swing.JButton bsub;
    private javax.swing.JButton cal;
    private javax.swing.JButton clear;
    private javax.swing.JButton cos;
    private javax.swing.JButton cr;
    private javax.swing.JButton cu;
    private javax.swing.JButton euler;
    private javax.swing.JButton exiter;
    private javax.swing.JButton exp;
    private javax.swing.JButton fac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton log;
    private javax.swing.JButton pi;
    private javax.swing.JButton prck;
    private javax.swing.JButton pw;
    private javax.swing.JButton rem;
    private javax.swing.JButton root;
    private javax.swing.JButton rub;
    private javax.swing.JTextField show;
    private javax.swing.JButton sin;
    private javax.swing.JButton sq;
    private javax.swing.JButton tan;
    private javax.swing.JTextField txt;
    private javax.swing.JButton unit;
    // End of variables declaration//GEN-END:variables

}
